apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: streams-grafana
spec:
  config:
    auth:
      disable_login_form: false
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      # will be changed after first login
      admin_password: admin
      admin_user: admin
  dashboardLabelSelector:
  - matchExpressions:
    - key: app
      operator: In
      values:
      - strimzi
  ingress:
    enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 200Mi
